apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: techdocker24/devopsexamapp:latest  # replace with your actual image
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql"
